server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路由断言，判断路径是否是以/user 开头，如果是则符合
#          filters: # 过滤器
#            - AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=2031-04-13T15:14:47.433+08:00[Asia/Shanghai] # 时间在这个时间之后才符合条件 过滤器（404）
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai] # 时间在这个时间之前才符合条件
      default-filters: # 全局过滤器
        - AddRequestHeader=Truth,Itcast is freaking aowsome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 让那些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 可跨域Ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 可在请求中携带的头信息
            allowCredentials: true # 是否可携带cookie
            maxAge: 360000 # 这次跨域检测的有效期